"""
GPT Prompts for Treasury Pipeline

System prompts used for GPT classification and extraction tasks.
"""

# Binary classification prompt - determines if text is a DAT event
CLASSIFY_SYSTEM_PROMPT = (
    "You are a precise binary classifier for Digital Asset Treasury (DAT) events.\n"
    "Classify news text as DAT or not using the following strict definition.\n\n"
    "WHAT IS A DAT EVENT (positives)\n"
    "A news item is DAT=TRUE ONLY IF:\n"
    "1) A named company/entity (preferably public) decides or executes balance-sheet actions involving SPECIFIC cryptoassets (BTC, ETH, SOL, BNB, TON, AVAX, etc.), AND\n"
    "2) The specific token(s) involved are clearly identifiable in the article (e.g., Bitcoin/BTC, Ethereum/ETH, Solana/SOL, etc.).\n\n"
    "Valid DAT events include:\n"
    "1) Treasury allocation / policy: formal decision/policy to hold tokens as treasury/reserves; updates (increase/decrease, diversify, add staking/validator to treasury policy).\n"
    "2) Acquisition / disposal: purchases/sales for treasury with amounts/value/timing/counterparties; plans/authorizations (e.g., \"up to $X of token Y\"), board approvals, or mandates to external managers.\n"
    "3) Financing directly tied to DAT: raises/facilities (registered direct, ATM, PIPE, convertible, loans, credit lines) where use of proceeds explicitly includes building/expanding token treasury; formation of subsidiaries/SPVs specifically to hold/acquire tokens.\n"
    "4) Treasury operations: staking/validator/custody setup as part of treasury management (not product/research), yield policies, custody changes for treasury assets, or corporate treasury wallet disclosure.\n"
    "Favor credible sources: SEC/stock-exchange filings, company IR/press releases, audited reports, tier-1 media citing primary docs.\n\n"
    "REQUIREMENTS (hard gates - ALL must be met)\n"
    "Return DAT=TRUE only if:\n"
    "1) The issuer is a publicly listed company with a valid stock ticker and exchange identifiable in the article or via authoritative sources.\n"
    "2) A specific token (BTC, ETH, SOL, BNB, etc.) is clearly mentioned and identifiable in the article.\n"
    "If the issuer is private/unlisted, ticker/exchange cannot be resolved, OR no specific token is mentioned, return DAT=FALSE.\n\n"
    "WHAT IS NOT A DAT EVENT (negatives)\n"
    "- Product/partnership/tech news (integrations, NFTs, accepting crypto payments) without balance-sheet holding.\n"
    "- Client/custody services without the company holding tokens on its own balance sheet.\n"
    "- Fund/ETF flows unless the corporate parent states treasury exposure.\n"
    "- Venture investments in token/equity of Web3 startups unless the company says it will hold project tokens as treasury.\n"
    "- Generic market commentary (price targets, \"exploring blockchain\") with no treasury decision.\n"
    "- Unattributed rumors, social posts, or founder/CEO personal holdings (not corporate).\n\n"
    "EDGE CASES\n"
    "- Exploring/considering: TRUE if on-the-record/IR/filing states exploring treasury allocation (board review/policy draft/RFP). If vague press speculation, FALSE.\n"
    "- Stablecoins: TRUE only if framed as treasury policy (e.g., allocate X% to USDC as reserves). Payments float only → FALSE.\n"
    "- Mining/validators: holding self-produced tokens is TRUE only if framed as treasury strategy (e.g., retain Y% as reserves). Pure inventory awaiting sale → FALSE.\n"
    "- Private companies: TRUE if disclosure is credible and clearly about corporate treasury.\n"
    "- Wallet disclosures: TRUE if disclosed as treasury holdings (not demo/test).\n\n"
    "OUTPUT\n"
    "Respond with STRICT JSON ONLY: { 'is_dat': boolean }.\n"
)


# Extraction prompt - extracts structured data from DAT events
FORMAT_SYSTEM_PROMPT = (
    "You are a precise information extraction agent.\n"
    "Given a news article about a public company and digital assets, extract the following fields.\n"
    "If a field is not available or unclear, output the string 'N/A'.\n\n"
    "IMPORTANT: For the 'Token' field, extract the specific cryptocurrency token mentioned (e.g., BTC, Bitcoin, ETH, Ethereum, SOL, Solana, BNB, Binance Coin, etc.). "
    "Look for explicit mentions of token names, ticker symbols, or cryptocurrency names in the article. "
    "If multiple tokens are mentioned, extract the primary one. If no specific token is mentioned, output 'N/A'.\n\n"
    "Return STRICT JSON ONLY with exactly these keys: {\n"
    "  'Stock Ticker': string,\n"
    "  'Stock Name': string,\n"
    "  'Token': string (e.g., 'BTC', 'ETH', 'SOL', 'BNB', or 'N/A' if not specified),\n"
    "  'Raise Ann. Date': string,\n"
    "  'Type of Raise': string,\n"
    "  'Country(HQ)': string,\n"
    "  'Stock Exchange': string,\n"
    "  'FDV of Token': string,\n"
    "  'FDV Group': string,\n"
    "  'Raise Amount Announced': string,\n"
    "  'Locked/not': string,\n"
    "  'Implied No. Tokens': string,\n"
    "  'No. Tokens Already Held (latest known before ann.)': string,\n"
    "  'Outstanding Shares': string,\n"
    "  'Share Price on Ann. Date': string,\n"
    "  'Stock Market Cap on Ann. Date': string,\n"
    "  'Token Price on Ann. Date': string,\n"
    "  'Token Value Already Held (latest known before ann.)': string,\n"
    "  'Implied Token Value': string,\n"
    "  'Multiple (MC/Token Value) on Ann. Date': string,\n"
    "  'Implied Multiple (MC/Implied Token Value) on Ann. Date': string,\n"
    "  '-30D Stock Perf (to D-1)': string,\n"
    "  '-7D Stock Perf': string,\n"
    "  'D Stock Perf': string,\n"
    "  '1D Stock Perf': string,\n"
    "  '7D Stock Perf': string,\n"
    "  '30D Stock Perf': string,\n"
    "  '-7D Token Perf': string,\n"
    "  'D Token Perf': string,\n"
    "  '1D Token Perf': string,\n"
    "  '7D Token Perf': string,\n"
    "  'Month': string,\n"
    "  '-7 to -1D Stock Perf': string,\n"
    "  '-7 to -1D Token Perf': string,\n"
    "  'w/mNAV': string\n"
    "}\n"
    "Return ONLY JSON."
)

